// <auto-generated />
using System;
using CashFlowApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CashFlowApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231212133458_MigracaoUsuario")]
    partial class MigracaoUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CashFlowApi.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TB_CATEGORIAS");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Salario"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Aluguel"
                        });
                });

            modelBuilder.Entity("CashFlowApi.Models.Lancamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoLancamento")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TB_LANCAMENTOS");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataLancamento = new DateTime(2023, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Salario de Novembro",
                            TipoLancamento = 2,
                            Valor = 5000.00m
                        },
                        new
                        {
                            Id = 2,
                            DataLancamento = new DateTime(2023, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Aluguel de Novembro",
                            TipoLancamento = 1,
                            Valor = 1200.00m
                        });
                });

            modelBuilder.Entity("CashFlowApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAcesso")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TB_USUARIOS");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = new byte[] { 206, 243, 185, 23, 34, 192, 218, 83, 162, 121, 140, 13, 173, 77, 152, 211, 244, 182, 242, 25, 98, 229, 11, 225, 27, 165, 247, 198, 245, 118, 181, 196, 72, 222, 97, 155, 229, 126, 11, 173, 209, 44, 8, 49, 59, 237, 45, 139, 158, 114, 166, 124, 126, 8, 252, 149, 246, 195, 234, 231, 2, 241, 223, 124 },
                            PasswordSalt = new byte[] { 37, 244, 38, 218, 235, 239, 172, 25, 240, 131, 113, 162, 184, 231, 169, 44, 76, 181, 196, 212, 76, 37, 75, 210, 77, 125, 47, 245, 45, 237, 210, 2, 160, 186, 206, 97, 201, 163, 25, 182, 146, 81, 39, 237, 119, 214, 185, 255, 5, 245, 132, 223, 149, 162, 185, 245, 45, 114, 238, 54, 132, 40, 210, 43, 177, 212, 153, 124, 24, 5, 75, 179, 45, 51, 234, 1, 180, 60, 26, 219, 35, 171, 72, 15, 246, 8, 251, 29, 216, 224, 106, 4, 128, 143, 1, 47, 109, 6, 224, 163, 206, 37, 181, 19, 211, 143, 132, 3, 56, 100, 151, 32, 18, 80, 241, 6, 185, 27, 222, 115, 147, 74, 208, 142, 253, 152, 217, 226 },
                            Username = "Admin"
                        });
                });

            modelBuilder.Entity("CashFlowApi.Models.Lancamento", b =>
                {
                    b.HasOne("CashFlowApi.Models.Usuario", "Usuario")
                        .WithMany("Lancamentos")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CashFlowApi.Models.Usuario", b =>
                {
                    b.Navigation("Lancamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
